-- 공통코드 정보 테이블
CREATE TABLE COMMON_CODE (
    COCO_CD CHAR(8) PRIMARY KEY NOT NULL,
    COCO_NAME VARCHAR2(50) NOT NULL,
    COCO_PARENT_ID CHAR(8),
    COCO_DELFLAG CHAR(1) DEFAULT 'N' NOT NULL,
    COCO_CREATE_ID CHAR(8) NOT NULL,
    COCO_CREATE_DT DATE DEFAULT CURRENT_DATE,
    COCO_MODIFY_ID CHAR(8),
    COCO_MODIFY_DT DATE
);

--권한코드 정보 테이블
CREATE TABLE AUTH_CODE (
    AUCO_CD VARCHAR2(20) PRIMARY KEY NOT NULL,
    AUCO_NAME VARCHAR2(50) NOT NULL,
    AUCO_DELFLAG CHAR(1) DEFAULT 'N' NOT NULL,
    AUCO_CREATE_ID CHAR(8) NOT NULL,
    AUCO_CREATE_DT DATE DEFAULT CURRENT_DATE,
    AUCO_MODIFY_ID CHAR(8),
    AUCO_MODIFY_DT DATE
);

-- 임직원 정보 테이블
CREATE TABLE EMPLOYEE (
    EMPL_ID CHAR(8) PRIMARY KEY NOT NULL,
    EMPL_PWD VARCHAR2(100) NOT NULL,
    EMPL_NAME VARCHAR2(20) NOT NULL,
    EMPL_BIRTH VARCHAR2(8) NOT NULL,
    EMPL_GENDER CHAR(1) NOT NULL,
    EMPL_EMAIL VARCHAR2(100) NOT NULL,
    EMPL_PHONE VARCHAR2(14) NOT NULL,
    EMPL_TEL VARCHAR2(3),
    EMPL_FAX VARCHAR2(14),
    EMPL_JOINDATE VARCHAR2(10) NOT NULL,
    EMPL_LEAVEDATE VARCHAR2(10),
    EMPL_PICTURE BLOB,
    EMPL_DEPT_CD CHAR(8) NOT NULL,
    EMPL_RANK_CD CHAR(8) NOT NULL,
    EMPL_POSITION_CD CHAR(8),
    EMPL_AUTH VARCHAR2(20) NOT NULL,
    EMPL_DELFLAG CHAR(1) DEFAULT 'N' NOT NULL,
    EMPL_LAST_LOGIN_DT DATE,
    EMPL_CREATE_ID CHAR(8) NOT NULL,
    EMPL_CREATE_DT DATE DEFAULT CURRENT_DATE NOT NULL,
    EMPL_MODIFY_ID CHAR(8),
    EMPL_MODIFY_DT DATE,
    CONSTRAINT FK_COMMON_CODE_DEPT FOREIGN KEY (EMPL_DEPT_CD) REFERENCES COMMON_CODE(COCO_CD),
    CONSTRAINT FK_COMMON_CODE_RANK FOREIGN KEY (EMPL_RANK_CD) REFERENCES COMMON_CODE(COCO_CD),
    CONSTRAINT FK_AUTH_CODE FOREIGN KEY (EMPL_AUTH) REFERENCES AUTH_CODE(AUCO_CD)
); 

-- 로그인 이력관리 테이블
CREATE TABLE EMP_LOGIN_HISTORY (
    EMLH_SEQ NUMBER PRIMARY KEY,
    EMPL_ID CHAR(8) NOT NULL,
    EMLH_CREATE_DT DATE DEFAULT CURRENT_DATE,
    EMLH_CREATE_IP VARCHAR2(15)
);

-- 서명관리 테이블
CREATE TABLE EMP_SIGN (
    EMSI_SEQ NUMBER PRIMARY KEY,
    EMPL_ID CHAR(8) NOT NULL,
    EMSI_TITLE VARCHAR2(100) NOT NULL,
    EMSI_SIGN_IMG CLOB,
    EMSI_STAMP_IMG BLOB,
    EMSI_DELFLAG CHAR(1) DEFAULT 'N' NOT NULL,
    EMSI_CREATE_ID CHAR(8) NOT NULL,
    EMSI_CREATE_DT DATE DEFAULT CURRENT_DATE,
    EMSI_MODIFY_ID CHAR(8),
    EMSI_MODIFY_DT DATE,
    CONSTRAINT FK_EMP_SIGN FOREIGN KEY (EMPL_ID) REFERENCES EMPLOYEE(EMPL_ID)
);

-- 회사정보관리
CREATE TABLE COMPANY (
    COMP_ID CHAR(8) PRIMARY KEY NOT NULL,
    COMP_NAME VARCHAR2(50) NOT NULL,
    COMP_NUM CHAR(12) NOT NULL,
    COMP_CEO_NAME VARCHAR2(20) NOT NULL,
    COMP_TEL VARCHAR2(15),
    COMP_FAX VARCHAR2(15),
    COMP_POST CHAR(5),
    COMP_ADDR1 VARCHAR2(50),
    COMP_ADDR2 VARCHAR2(50),
    COMP_SEAL BLOB,
    COMP_CREATE_ID CHAR(8) NOT NULL,
    COMP_CREATE_DT DATE DEFAULT CURRENT_DATE NOT NULL,
    COMP_MODIFY_ID CHAR(8),
    COMP_MODIFY_DT DATE
);

-- 문서번호관리 테이블
CREATE TABLE EMP_DOC_NUM (
    EMDN_ID CHAR(8) PRIMARY KEY NOT NULL,
    EMPL_ID CHAR(8),
    EMDN_CREATE_DT DATE DEFAULT CURRENT_DATE,
    CONSTRAINT FK_EMP_DOC_NUM FOREIGN KEY (EMPL_ID) REFERENCES EMPLOYEE(EMPL_ID)
);

-- 문서발급 이력관리 테이블
CREATE TABLE EMP_DOC_HISTORY (
    EMDH_SEQ NUMBER PRIMARY KEY,
    EMDN_ID CHAR(8) NOT NULL,
    EMDH_EMPL_ID CHAR(8) NOT NULL,
    EMDH_TYPE CHAR(1),
    EMDH_CREATE_DT DATE DEFAULT CURRENT_DATE,
    CONSTRAINT FK_EMP_DOC_HISTORY_EMP_DOC_NUM FOREIGN KEY (EMDN_ID) REFERENCES EMP_DOC_NUM(EMDN_ID)
);

-- 인사발령 테이블
CREATE TABLE EMP_ORDER (
    EMOR_ID CHAR(8) PRIMARY KEY NOT NULL,
    EMOR_STATUS CHAR(1) DEFAULT 'N' NOT NULL,
    EMOR_CREATE_ID CHAR(8) NOT NULL,
    EMOR_CREATE_DT DATE DEFAULT CURRENT_DATE NOT NULL,
    EMOR_MODIFY_ID CHAR(8),
    EMOR_MODIFY_DT DATE
);

-- 인사발령 상세 테이블
CREATE TABLE EMP_ORDER_DETAIL (
    EMOR_ID CHAR(8) NOT NULL,
    EMOD_SEQ NUMBER NOT NULL,
    EMPL_ID CHAR(8) NOT NULL,
    EMOD_ORDER_DT CHAR(10) NOT NULL,
    EMOD_TYPE CHAR(8) NOT NULL,
    EMOD_PREV_DEPT CHAR(8),
    EMOD_ORDER_DEPT CHAR(8),
    EMOD_PREV_RANK CHAR(8),
    EMOD_ORDER_RANK CHAR(8),
    EMOD_PREV_POSITION CHAR(8),
    EMOD_ORDER_POSITION CHAR(8),
    EMOD_CREATE_ID CHAR(8) NOT NULL,
    EMOD_CREATE_DT DATE DEFAULT CURRENT_DATE,
    EMOD_MODIFY_ID CHAR(8),
    EMOD_MODIFY_DT DATE,
    PRIMARY KEY (EMOR_ID, EMOD_SEQ),
    CONSTRAINT FK_EMP_ORDER_DETAIL_EMP_ORDER FOREIGN KEY (EMOR_ID) REFERENCES EMP_ORDER(EMOR_ID)
);

-- 근태관리 테이블
CREATE TABLE EMP_COMMUTE (
    EMCO_SEQ NUMBER PRIMARY KEY,
    EMPL_ID CHAR(8) NOT NULL,
    EMCO_IN_DT DATE,
    EMCO_OUT_DT DATE,
    CONSTRAINT FK_EMP_COMMUTE_EMPLOYEE FOREIGN KEY (EMPL_ID) REFERENCES EMPLOYEE(EMPL_ID)
);

-- 공휴일관리 테이블
CREATE TABLE HOLIDAY (
    HOLI_DATE CHAR(10) PRIMARY KEY NOT NULL,
    HOLI_NAME VARCHAR2(50),
    HOLI_FLAG CHAR(1),
    HOLI_CREATE_ID CHAR(8) NOT NULL,
    HOLI_CREATE_DT DATE DEFAULT CURRENT_DATE,
    HOLI_MODIFY_ID CHAR(8),
    HOLI_MODIFY_DT DATE
);

-- 간편로그인 테이블
CREATE TABLE EMP_SNS (
    EMSN_ID VARCHAR2(50) PRIMARY KEY NOT NULL,
    EMPL_ID CHAR(8) NOT NULL,
    EMSN_EMAIL VARCHAR2(50) NOT NULL,
    EMSN_CREATE_DT DATE,
    CONSTRAINT FK_EMP_SNS_EMPLOYEE FOREIGN KEY (EMPL_ID) REFERENCES EMPLOYEE(EMPL_ID)
);

--총 휴가일 정보
CREATE TABLE EMP_HOLIDAY (
    EMHO_YEAR CHAR(4) NOT NULL,
    EMPL_ID CHAR(8) NOT NULL,
    EMHO_HOLIDAY NUMBER NOT NULL,
    EMHO_CREATE_DT DATE DEFAULT CURRENT_DATE,
    PRIMARY KEY (EMHO_YEAR, EMPL_ID),
    CONSTRAINT FK_EMP_HOLIDAY FOREIGN KEY (EMPL_ID) REFERENCES EMPLOYEE(EMPL_ID)
);

-- 공지사항게시판 테이블
CREATE TABLE GONGJI_BOARD (
    GOBO_NO NUMBER PRIMARY KEY NOT NULL,
    GOBO_TITLE VARCHAR2(200) NOT NULL,
    GOBO_CONTENT CLOB,
    GOBO_VIEW NUMBER,
    GOBO_WRITER VARCHAR2(20) NOT NULL,
    GOBO_WRITER_ID CHAR(8),
    GOBO_REGDATE DATE DEFAULT SYSDATE NOT NULL,
    GOBO_MODIFY_ID CHAR(8),
    GOBO_MODIFY_DATE DATE DEFAULT SYSDATE,
    GOBO_DELFLAG CHAR(1) DEFAULT 'N' NOT NULL,
    GOBO_BIGO VARCHAR2(200)
);

-- 공지사항 댓글관리 테이블
CREATE TABLE REPLY_BOARD (
    REBO_SEQ NUMBER PRIMARY KEY NOT NULL,
    GOBO_NO NUMBER,
    REBO_CONTENT CLOB,
    REBO_WRITER VARCHAR2(40) NOT NULL,
    REBO_WRITER_ID CHAR(8) NOT NULL,
    REBO_REGDATE DATE DEFAULT SYSDATE NOT NULL,
    REBO_MODIFY_ID CHAR(8),
    REBO_MODIFY_DATE DATE DEFAULT SYSDATE,
    REBO_STEP NUMBER,
    REBO_DELFLAG CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT fk_reply_board_gongji FOREIGN KEY (GOBO_NO) REFERENCES GONGJI_BOARD(GOBO_NO)
);

-- 캘린더 테이블
CREATE TABLE CALENDAR (
    CALE_SEQ NUMBER PRIMARY KEY NOT NULL,
    CALE_ROOT_SEQ NUMBER NOT NULL,
    CALE_CGORY_NO NUMBER NOT NULL,
    CALE_TITLE VARCHAR2(200) NOT NULL,
    CALE_START DATE NOT NULL,
    CALE_END DATE,
    CALE_COLOR VARCHAR2(20)
);

-- 일정관리 테이블
CREATE TABLE SCHEDULE_BOARD (
    SCBO_NO NUMBER PRIMARY KEY NOT NULL,
    SCBO_CGORY_NO NUMBER NOT NULL,
    SCBO_EMPNO NUMBER NOT NULL,
    SCBO_WRITER VARCHAR2(20) NOT NULL,
    SCBO_TITLE VARCHAR2(200) NOT NULL,
    SCBO_CONTENT VARCHAR2(2000),
    SCBO_REGDATE DATE DEFAULT SYSDATE NOT NULL,
    SCBO_START DATE NOT NULL,
    SCBO_END DATE,
    SCBO_MODIFY_ID CHAR(8) NOT NULL,
    SCBO_MODIFY_DATE DATE DEFAULT SYSDATE NOT NULL,
    SCBO_BIGO VARCHAR2(200),
    SCBO_DELFLAG CHAR(1) DEFAULT 'N' NOT NULL
);

-- 결재구분 테이블
CREATE TABLE SIGN_CATEGORY (
    SICA_CD CHAR(8) PRIMARY KEY NOT NULL,
    SICA_NAME VARCHAR2(20) NOT NULL
);

-- 결재템플릿 테이블
CREATE TABLE SIGN_DOC_TEMP (
    SIDT_TEMP_CD CHAR(8) PRIMARY KEY NOT NULL,
    SICA_CD CHAR(8) NOT NULL,
    SIDT_TEMP_NAME VARCHAR2(20) NOT NULL,
    SIDT_TEMP_CREATEDT DATE NOT NULL,
    SIDT_TEMP_MODIFYDT DATE,
    SIDT_TEMP_FLAG CHAR(1) DEFAULT 'Y' NOT NULL,
    CONSTRAINT FK_SIGN_DOC_TEMP_CATEGORY FOREIGN KEY (SICA_CD) REFERENCES SIGN_CATEGORY(SICA_CD)
);

-- 결재문서함 테이블
CREATE TABLE SIGN_DOC_BOX (
    SIDB_DOC_NUM NUMBER(8) PRIMARY KEY NOT NULL,
    SIDB_DOC_WRITEDT DATE DEFAULT CURRENT_DATE NOT NULL,
    EMPL_ID CHAR(8) NOT NULL,
    SIDB_DOC_TITLE VARCHAR2(100) NOT NULL,
    SIDB_DOC_CONTENT CLOB NOT NULL,
    SICA_CD CHAR(8) NOT NULL,
    SIDB_DOC_EXPIREDT DATE NOT NULL,
    SIDB_DOC_FLAG CHAR(1),
    SIDB_DOC_APPRDT DATE,
    SIDB_DOC_DELFLAG CHAR(1) DEFAULT 'N' NOT NULL,
    SIDB_DOC_ALFLAG CHAR(1) DEFAULT 'N' NOT NULL,
    SIDB_DOC_STAT CHAR(1) DEFAULT '1' NOT NULL,
    SIDB_DOC_MODIFYDT DATE,
    SIDT_TEMP_CD CHAR(8) NOT NULL,
    SIDB_DOC_JSON CLOB NOT NULL,
    EMPL_REF VARCHAR2(200),
    EMPL_DEPT_CD VARCHAR2(200),
    SIDB_DOC_BE DATE,
    SIDB_DOC_END DATE,
    CONSTRAINT FK_SIGN_DOC_BOX_CATEGORY FOREIGN KEY (SICA_CD) REFERENCES SIGN_CATEGORY(SICA_CD),
    CONSTRAINT FK_SIGN_DOC_BOX_TEMP FOREIGN KEY (SIDT_TEMP_CD) REFERENCES SIGN_DOC_TEMP(SIDT_TEMP_CD)
);

-- 결재 첨부 파일 테이블
CREATE TABLE SIGN_DOC_FILE (
    SIDF_FILE_NUM NUMBER(8) PRIMARY KEY NOT NULL,
    SIDB_DOC_NUM NUMBER(8) NOT NULL,
    SIDF_FILE_ORIGIN VARCHAR2(100) NOT NULL,
    SIDF_FILE_STORED VARCHAR2(100) NOT NULL,
    SIDF_FILE_SIZE VARCHAR2(200) NOT NULL,
    SIDF_FILE_CONTENT BLOB NOT NULL,
    SIDF_FILE_FLAG CHAR(1) DEFAULT 'N' NOT NULL,
    CONSTRAINT FK_SIGN_DOC_FILE_BOX FOREIGN KEY (SIDB_DOC_NUM) REFERENCES SIGN_DOC_BOX(SIDB_DOC_NUM)
);

-- 트리뷰
CREATE TABLE SIGN_DOC_TREE (
    ID VARCHAR2(10) PRIMARY KEY NOT NULL,
    PARENT VARCHAR2(10) NOT NULL,
    TEXT VARCHAR2(100) NOT NULL,
    ICON VARCHAR2(100),
    POS_NA VARCHAR2(100),
    POS_FLAG CHAR(1)
);

-- 결재즐겨찾기
CREATE TABLE SIGN_APPR_FAVO (
    SIAF_FAVO_CD CHAR(8) PRIMARY KEY NOT NULL,
    EMPL_ID CHAR(8),
    SIAF_FAVO_NAME VARCHAR2(100),
    SIAF_APPR_ID VARCHAR2(500),
    SIAF_APPR_LINE VARCHAR2(1000),
    SIAF_APPR_FLAG CHAR(1) NOT NULL,
    CONSTRAINT FK_SIGN_APPR_FAVO FOREIGN KEY (EMPL_ID) REFERENCES EMPLOYEE(EMPL_ID)
);


