-- 결재구분 DATA
INSERT INTO SIGN_CATEGORY (SICA_CD, SICA_NAME)
VALUES('CC000001', '근태');
INSERT INTO SIGN_CATEGORY (SICA_CD, SICA_NAME)
VALUES('CC000002', '품의');
INSERT INTO SIGN_CATEGORY (SICA_CD, SICA_NAME)
VALUES('CC000003', '업무');
INSERT INTO SIGN_CATEGORY (SICA_CD, SICA_NAME)
VALUES('CC000004', '보고');
INSERT INTO SIGN_CATEGORY (SICA_CD, SICA_NAME)
VALUES('CC000005', '증명');

-- 결재템플릿 DATA
INSERT INTO SIGN_DOC_TEMP (SIDT_TEMP_CD, SICA_CD, SIDT_TEMP_NAME, SIDT_TEMP_CREATEDT)
VALUES('TC000001','CC000001','연차신청서', CURRENT_TIMESTAMP);
INSERT INTO SIGN_DOC_TEMP (SIDT_TEMP_CD, SICA_CD, SIDT_TEMP_NAME, SIDT_TEMP_CREATEDT)
VALUES('TC000002','CC000001','휴가신청서', CURRENT_TIMESTAMP);
INSERT INTO SIGN_DOC_TEMP (SIDT_TEMP_CD, SICA_CD, SIDT_TEMP_NAME, SIDT_TEMP_CREATEDT)
VALUES('TC000003','CC000001','경조사신청서', CURRENT_TIMESTAMP);
INSERT INTO SIGN_DOC_TEMP (SIDT_TEMP_CD, SICA_CD, SIDT_TEMP_NAME, SIDT_TEMP_CREATEDT)
VALUES('TC000004','CC000001','사직서', CURRENT_TIMESTAMP);
INSERT INTO SIGN_DOC_TEMP (SIDT_TEMP_CD, SICA_CD, SIDT_TEMP_NAME, SIDT_TEMP_CREATEDT)
VALUES('TC000005','CC000002','지출결의서', CURRENT_TIMESTAMP);
INSERT INTO SIGN_DOC_TEMP (SIDT_TEMP_CD, SICA_CD, SIDT_TEMP_NAME, SIDT_TEMP_CREATEDT)
VALUES('TC000006','CC000002','출장신청서', CURRENT_TIMESTAMP);
INSERT INTO SIGN_DOC_TEMP (SIDT_TEMP_CD, SICA_CD, SIDT_TEMP_NAME, SIDT_TEMP_CREATEDT)
VALUES('TC000007','CC000002','구매신청서', CURRENT_TIMESTAMP);
INSERT INTO SIGN_DOC_TEMP (SIDT_TEMP_CD, SICA_CD, SIDT_TEMP_NAME, SIDT_TEMP_CREATEDT)
VALUES('TC000008','CC000002','승진신청서', CURRENT_TIMESTAMP);
INSERT INTO SIGN_DOC_TEMP (SIDT_TEMP_CD, SICA_CD, SIDT_TEMP_NAME, SIDT_TEMP_CREATEDT)
VALUES('TC000009','CC000003','업무일지', CURRENT_TIMESTAMP);
INSERT INTO SIGN_DOC_TEMP (SIDT_TEMP_CD, SICA_CD, SIDT_TEMP_NAME, SIDT_TEMP_CREATEDT)
VALUES('TC000010','CC000003','회의록', CURRENT_TIMESTAMP);
INSERT INTO SIGN_DOC_TEMP (SIDT_TEMP_CD, SICA_CD, SIDT_TEMP_NAME, SIDT_TEMP_CREATEDT)
VALUES('TC000011','CC000004','회의보고서', CURRENT_TIMESTAMP);
INSERT INTO SIGN_DOC_TEMP (SIDT_TEMP_CD, SICA_CD, SIDT_TEMP_NAME, SIDT_TEMP_CREATEDT)
VALUES('TC000012','CC000004','업무보고서', CURRENT_TIMESTAMP);
INSERT INTO SIGN_DOC_TEMP (SIDT_TEMP_CD, SICA_CD, SIDT_TEMP_NAME, SIDT_TEMP_CREATEDT)
VALUES('TC000013','CC000004','출장보고서', CURRENT_TIMESTAMP);
INSERT INTO SIGN_DOC_TEMP (SIDT_TEMP_CD, SICA_CD, SIDT_TEMP_NAME, SIDT_TEMP_CREATEDT)
VALUES('TC000014','CC000005','재직증명서', CURRENT_TIMESTAMP);

